export const songFunction = songs => {
  let songObjects = []
  songs.forEach(song => {
    const init = song.indexOf('(')
    const fin = song.indexOf(')')
    const songArtist = song.substr(init + 1, fin - init - 1)
    //console.log('SONG_ARTIST', songArtist)
    const songTitle = song
      .replace(songArtist, '')
      .replace('()', '')
      .trim()
    const res = {
      title: songTitle,
      artist: songArtist,
    }
    songObjects.push(res)
  })
  return songObjects
}

export const songStrings = [
  '500 Miles (The Proclaimers)',
  '7 Nation Army (White Stripes)',
  '99 Red Balloons (Goldfiner)',
  'All I Have to Do is Dream (Everly Brothers)',
  'All The Small Things (Blink 182)',
  'American Girl (Tom Petty)',
  'Angel Down (Lady Gaga)',
  'Another Kind of Green (John Mayer)',
  'Another Saturday Night (Cat Stevens)',
  'Bad Moon Rising (CCR)',
  'Beverly HIlls (Weezer)',
  'Bizzare Love Triangle (Frente)',
  'Blister in the Sun (Violent Fems)',
  'Boulevard of Broken Dreams (Green Day)',
  "Breakfast at Tiffeny's (Deep Blue Something)",
  'Breaking the Girl (RHCP)',
  'Bye Bye Love (Everly Brothers)',
  "Can't Help Falling in Love with You (Elvis)",
  "Can't Stop (RHCP)",
  'Ceiling Four Walls and a Floor (Johnny Cash)',
  'Chicken Fried ( Zak Brown Band)',
  'Cleopatra (The Lumineers)',
  'Cocain Blues (Johnny Cash)',
  'Country Roads (John Denver)',
  'Crazy Little Thing Called Love (Queen)',
  "Don't You Want Me Baby (Human League)",
  'Edge of Desire  (John Mayer)',
  'Eight Days A Week (Beatles)',
  'Everlong (Foo Fighters)',
  'Folsom Prison Blues (Johnny Cash)',
  'Forever and Ever Amen (Randy Jackson)',
  'Fortunate Son (CCR)',
  'Free Falling (Tom Petty)',
  "Friday I'm In Love (The Cure)",
  'Friends in California (Johnny Cash)',
  'Fuck Her Gently (Tenacious D)',
  'Glycerin (Bush)',
  'Good (Better Than Ezra)',
  'Gravity (John Mayer)',
  'Grigio Girls (Lady Gaga)',
  'Grow Old With You (Adam Sandler)',
  'Have You Ever Seen the Rain (CCR)',
  'Heartbreak Warfare (John Mayer)',
  'Hey Brother (Avicii)',
  'Ho Hey (The Lumineers)',
  'Hold My Hand (Hootie and the Blowfish)',
  'Hot and Cold (Katy Perry)',
  'Hotel Yorba (The White Stripes)',
  'Hunger Strike (Temple of the Dog)',
  'Hurt (Johny Cash)',
  'Hurt So Good (JCC)',
  'Hysterical (Yeah Yeah Yeahs)',
  'I Got A Woman (Ray Charles)',
  'I Wanna Be Sedated (The Ramones)',
  "I'm Gonna Find Another You (John Mayer)",
  'Ibiza (Mike Posner)',
  'In the Blood (John Mayer)',
  'Joanne (Lady Gaga)',
  'Jolene (White Striipes)',
  'Jumper (Third Eye Blind)',
  "Knocking on Heavens Door (G'n'R)",
  'La Bamba (Richie Valentine)',
  'Last Dance With Mary Jane (Tom Petty)',
  'Last Kiss (Pearl Jam)',
  'Last Thing I Needed (Willie Nelson)',
  'Learning to Fly (Tom Petty)',
  'Leaving On a Jetplane (John Denver)',
  'Let Her Cry (Hootie and the Blowfish)',
  'Lithium (Nirvana)',
  'Lodi (CCR)',
  'Long Time Gone (Everly Brothers)',
  'Longview (Green Day)',
  'Looking Out My Back Door (CCR)',
  'Love (Lana Del Rey)',
  'Love is a Verb (John Mayer)',
  'Love on the Weekend (John Mayer)',
  'Love Yourself (Justin Beiber)',
  'Machinehead (Bush)',
  'Man In The Box (Alice In Chains)',
  'Million Reasons (Lady Gaga)',
  'My Name is Jonas (Weezer)',
  'Norwegian Wood (The Beatles)',
  'Nothing Compares (Chris Cornell Version)',
  'Ob La Di (The Beatles)',
  'Ophelia (The Lumineers)',
  'Pancho and Lefty (Willy Nelson)',
  'Peaches (Pres of USA)',
  'Polly (Nirvanna)',
  'Pride and Joy (SRV)',
  'Rambling Man (Alman Brothers)',
  'Redemption Song (Bob Marley)',
  'Ring of fire (Johnny Cash)',
  'Ring of Fire (Nirvana)',
  'Rocking in the Free World (Neil Young)',
  'Santa is Coming to Town (MIsc)',
  'Santeria (Sublime)',
  'Scar Tissue (RHCP)',
  'Shine (Collective Soul)',
  'Simple Man (Skynard)',
  'Slow Dancing in a Burning Room (John Mayer)',
  'Someday (The Strokes)',
  'Something Like Olivia (John Mayer)',
  'Space Oddity (David Bowie)',
  'Stand by Me ( Ben King)',
  'Stop This Train (John Mayer)',
  'Summer of 69 (Bryan Adams)',
  'Sweet Baby James (James Taylor)',
  'Take Me Out (Franz Ferdinand)',
  'The Denial Twist (The White Stripes)',
  'The Impression That I Get (Mighty Mighty Bosstones)',
  'The Lion Sleeps Tonight (The Tokens)',
  'The Rooster (Alice in Chains)',
  'The Times They are a Changing (Bob Dylan)',
  'The Waiting (Tom Petty)',
  'The Way (Fastball)',
  'Two of Us  (The Beatles)',
  'Under the Bridge (RHCP)',
  'Video Games (Lana Del Rey)',
  'Voodoo Child (Jimmy Hendrix)',
  'Wagon Wheel (Nobody Cares)',
  'Want You To Want Me (Cheap Trick)',
  "We're Gonna Be Friends (The White Stripes)",
  "What's Up (Three Non Blonds)",
  'When Will I Be Loved (Everly Brothers)',
  'Whisky Lullby (Brad Paisly)',
  'White Rabbit (Jefferson Airplane)',
  'Who Says (John Mayer)',
  "Who's Gonna Shoe Your Pretty Little Feet (Everly Brothers)",
  'Wildflowers (Tom Petty)',
  'Will You Still Love Me Tomorrow (Amy Weinhouse)',
  'With a Little Help From My Friends (The Beatles)',
  'Yesterday (The Beatles)',
  "You Don't Know How it Feels to be Me (Tom Petty)",
  'You Wreck Me (Tom Petty)',
]
